spring.application.name=LoanApplicationAssignment

# Data source
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_application}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=false

# Business policy for loan applications.

lendo.loan-policy.min-amount=1000.00
lendo.loan-policy.max-amount=5000000.00
lendo.loan-policy.min-loan-terms=1
lendo.loan-policy.max-loan-terms=360